### ISSUE TITLE
Errors under Smarty4

### ISSUE THREAD

**Issue by twomice** [JoineryHQ/com.joineryhq.dupmon#4]
As reported by @Chipleh12 in a [comment on #3](https://github.com/JoineryHQ/com.joineryhq.dupmon/issues/3#issuecomment-2405994782):

> Also, one more note - we just started working with your extension today and found that it is not compatible with Smarty 4, there is no logging in ConfigAndLog around this error, but when enabling WP debugging, I see:
>
>Fatal error: Uncaught TypeError: Unsupported operand types: string - string in /files/civicrm/templates_c/en_US/e9/56/8c/e9568c6b86e881f602d414528319c6b66bb1f04f_0.file.DupmonBatches.tpl.php:36 Stack trace: #0 /code/wp-content/plugins/civicrm/civicrm/packages/smarty4/vendor/smarty/smarty/libs/sysplugins/smarty_template_resource_base.php(123): content_67083a2e1f62d3_82260059(Object(Smarty_Internal_Template))
>
>...the stack trace contains 25 more lines.
>
>This occurs when navigating to Dedupe Monitor > Settings or Scanned Batches.
>
>Hope this helps, let me know if I can provide any more info.

**Comment by michaelmcandrew** [comment]
Hey @twomice - we got hit by this one too on smarty 5. The missing quotes on "fa-rocket".

We've hot fixed it for now but is it easy to publish a new fixed release?

**Comment by twomice** [comment]
Thanks @michaelmcandrew I've tagged v1.2.1, c.o release should auto-generate within 24 hours.

**Comment by michaelmcandrew** [comment]
Thanks @twomice - appreciate it!
